### ISSUE TITLE
dfm training error: ValueError: need at least one array to stack

### ISSUE THREAD

**Issue by lhiceu** [Tai-Wang/Depth-from-Motion#12]
你好。我在尝试在KITTI训练dfm，但是遇到了“ValueError: need at least one array to stack”报错。

我有点怀疑是data preparation步骤出了问题。根据readme的步骤需要将KITTI raw和Kinematic3D提供的raw_extra合并，而我之前训练过Kinematic3D，发现有些KITTI3D训练集的图片在raw里是没有对应的前三帧。所以我怀疑这个bug因为缺少前三帧导致的。
ImageSetst我是从mmdetection3d下载的，data preparation时是不是要删除ImageSetst中缺少数据的samples？

还有其他原因导致了这个bug吗？

配置与部分终端输出如下：
```
python tools/train.py configs/dfm/dfm_r34_1x8_kitti-3d-3class.py --work-dir /media/he/Disk/Depth-from-Motion-main/ex_1 --gpus 1 --gpu-id 0
/home/he/anaconda3/envs/dfm/lib/python3.7/site-packages/MinkowskiEngine/__init__.py:42: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  "It is recommended to set it below 24.",
tools/train.py:150: UserWarning: `--gpus` is deprecated because we only support single GPU mode in non-distributed training. Use `gpus=1` now.
  warnings.warn('`--gpus` is deprecated because we only support '
fatal: not a git repository (or any parent up to mount point /media/he)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2022-09-08 13:03:24,967 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1080
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 10.1, V10.1.24
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - Built with CUDA Runtime 11.2
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_50,code=compute_50
  - CuDNN 8.2.1  (built against CUDA 11.3)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.2, CUDNN_VERSION=8.2.1, CXX_COMPILER=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1627802491209/_build_env/bin/x86_64-conda-linux-gnu-c++, CXX_FLAGS=-std=c++14 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1627802491209/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1627802491209/work=/usr/local/src/conda/pytorch-1.9.0 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1627802491209/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix -I/usr/local/cuda/include -Wno-deprecated-declarations -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=1, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0
OpenCV: 4.6.0
MMCV: 1.5.0
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 10.1
MMDetection: 2.24.0
MMSegmentation: 0.20.0
MMDetection3D: 1.0.0rc3+
spconv2.0: False
```
```
2022-09-08 13:03:29,693 - mmdet - INFO - workflow: [('train', 1)], max: 60 epochs
2022-09-08 13:03:29,693 - mmdet - INFO - Checkpoints will be saved to /media/he/Disk/Depth-from-Motion-main/ex_1 by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 259, in main
    meta=meta)
  File "/media/he/Disk/Depth-from-Motion-main/mmdet3d/apis/train.py", line 351, in train_model
    meta=meta)
  File "/media/he/Disk/Depth-from-Motion-main/mmdet3d/apis/train.py", line 319, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/he/anaconda3/envs/dfm/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/he/anaconda3/envs/dfm/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/he/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/he/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/he/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/he/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/he/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/he/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/he/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/he/Disk/Depth-from-Motion-main/mmdet3d/datasets/custom_3d.py", line 434, in __getitem__
    data = self.prepare_train_data(idx)
  File "/media/he/Disk/Depth-from-Motion-main/mmdet3d/datasets/custom_3d.py", line 228, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/media/he/Disk/Depth-from-Motion-main/mmdet3d/datasets/pipelines/compose.py", line 49, in __call__
    data = t(data)
  File "/media/he/Disk/Depth-from-Motion-main/mmdet3d/datasets/pipelines/loading.py", line 541, in __call__
    base_results['cur2prevs'] = np.stack(cur2prevs, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/he/anaconda3/envs/dfm/lib/python3.7/site-packages/numpy/core/shape_base.py", line 422, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```

**Comment by Tai-Wang** [comment]
感觉像是 cur2prevs 出了问题，请问你有改过 config 或者可以看下生成的 info 里有没有 cam2global 的值？如果没有前面帧应该默认会复制当前帧来作为之前一帧，这种情况是可以兼容的，应该不是问题原因。

**Comment by lhiceu** [comment]
> 感觉像是 cur2prevs 出了问题，请问你有改过 config 或者可以看下生成的 info 里有没有 cam2global 的值？如果没有前面帧应该默认会复制当前帧来作为之前一帧，这种情况是可以兼容的，应该不是问题原因。

因为训练时会报"核心已转储"的错误，我删掉了config中`dict(type='TensorboardLoggerHook')`，没有修改其他内容。
我查看了生成的`/Depth-from-Motion-main/data/kitti/kitti_infos_train.pkl`文件，所有sample的 `cam2global`都有值，但是`sweeps`全部是空。我不太理解sweeps的作用，为何是空的，是不是导致训练bug的原因。

'image':{'image_idx': 0, 'image_path': 'training/image_2/000000.png', 'sweeps': [], 'cam2global': array([[ 9.99964e-01,  3.81000e-04, -8.47700e-03,  1.59560e-02],
       [-3.83000e-04,  1.00000e+00, -2.50000e-04, -6.48600e-02],
       [ 8.47700e-03,  2.53000e-04,  9.99964e-01,  1.18648e-01],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  1.00000e+00]]), 'image_shape': array([ 370, 1224], dtype=int32)}

**Comment by hly2990** [comment]
> 

您好，请问您是怎么解决这个问题的？prev_2是指什么？

**Comment by hly2990** [comment]
> > 
> 
>@lhiceu  您好，请问您是怎么解决这个问题的？prev_2是指什么？
